# Generated by Django 3.1.2 on 2020-11-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
