# Generated by Django 3.1.2 on 2020-10-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_auto_20201026_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Password'),
        ),
    ]
