# Generated by Django 3.1.2 on 2020-10-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_auto_20201028_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividades',
            new_name='Actividad',
        ),
    ]
