# Generated by Django 3.1.2 on 2020-11-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0010_auto_20201113_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuario_id',
            field=models.ManyToManyField(to='calendario.usuario'),
        ),
    ]
