# Generated by Django 3.1.2 on 2020-11-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0011_auto_20201119_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='horaFinal',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='horaInicial',
        ),
        migrations.AddField(
            model_name='actividad',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fechaInicial',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
    ]
