# Generated by Django 3.1.2 on 2020-11-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0012_auto_20201119_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fechaInicial',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='usuario_id',
            field=models.ManyToManyField(to='calendario.Usuario'),
        ),
    ]
