# Generated by Django 3.1.2 on 2020-11-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0014_auto_20201128_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='usuario_id',
            field=models.ManyToManyField(to='calendario.Usuario'),
        ),
    ]
